# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
#
# Seed data: a curated snapshot of stations pulled from the Radio Browser community database
# (https://www.radio-browser.info/), a crowd-sourced, freely licensed directory of internet radio
# stations. Fetched once and embedded here as static data so `db:seed` doesn't depend on network
# access or a third-party API being up.

LOCATIONS = [
  { location: "Nationwide", country: "Spain", continent: "Europe" },
  { location: "Ibiza", country: "Spain", continent: "Europe" },
  { location: "Málaga", country: "Spain", continent: "Europe" },
  { location: "Lazio", country: "Italy", continent: "Europe" },
  { location: "Lombardia", country: "Italy", continent: "Europe" },
  { location: "Nationwide", country: "Italy", continent: "Europe" },
  { location: "Nationwide", country: "France", continent: "Europe" },
  { location: "Rheinland-Pfalz", country: "Germany", continent: "Europe" },
  { location: "Bavaria", country: "Germany", continent: "Europe" },
  { location: "North Rhine-Westphalia", country: "Germany", continent: "Europe" },
  { location: "Schleswig-Holstein", country: "Germany", continent: "Europe" },
  { location: "Nationwide", country: "United Kingdom", continent: "Europe" },
  { location: "London", country: "United Kingdom", continent: "Europe" },
  { location: "Lisbon", country: "Portugal", continent: "Europe" },
  { location: "Nationwide", country: "Portugal", continent: "Europe" },
  { location: "Burgenland", country: "Netherlands", continent: "Europe" },
  { location: "Nationwide", country: "Netherlands", continent: "Europe" },
  { location: "Nationwide", country: "Sweden", continent: "Europe" },
  { location: "Skåne", country: "Sweden", continent: "Europe" },
  { location: "Nationwide", country: "Poland", continent: "Europe" },
  { location: "Athens", country: "Greece", continent: "Europe" },
  { location: "Kefalonia", country: "Greece", continent: "Europe" },
  { location: "Nationwide", country: "Greece", continent: "Europe" },
  { location: "Nationwide", country: "Japan", continent: "Asia" },
  { location: "Nationwide", country: "China", continent: "Asia" },
  { location: "Kwangtung", country: "China", continent: "Asia" },
  { location: "Nationwide", country: "India", continent: "Asia" },
  { location: "Kolkata", country: "India", continent: "Asia" },
  { location: "West Bengal", country: "India", continent: "Asia" },
  { location: "Nationwide", country: "South Korea", continent: "Asia" },
  { location: "Seoul", country: "South Korea", continent: "Asia" },
  { location: "Nationwide", country: "Thailand", continent: "Asia" },
  { location: "Bangkok", country: "Thailand", continent: "Asia" },
  { location: "Tak", country: "Thailand", continent: "Asia" },
  { location: "Jakarta", country: "Indonesia", continent: "Asia" },
  { location: "Nationwide", country: "Indonesia", continent: "Asia" },
  { location: "Jawa Timur", country: "Indonesia", continent: "Asia" },
  { location: "Nationwide", country: "Philippines", continent: "Asia" },
  { location: "Manila", country: "Philippines", continent: "Asia" },
  { location: "Nationwide", country: "Israel", continent: "Asia" },
  { location: "Quebec", country: "Canada", continent: "North America" },
  { location: "Ontario", country: "Canada", continent: "North America" },
  { location: "California", country: "United States", continent: "North America" },
  { location: "New York NY", country: "United States", continent: "North America" },
  { location: "Wisconsin", country: "United States", continent: "North America" },
  { location: "Ciudad de México", country: "Mexico", continent: "North America" },
  { location: "Nationwide", country: "Mexico", continent: "North America" },
  { location: "Distrito Federal", country: "Mexico", continent: "North America" },
  { location: "São Paulo", country: "Brazil", continent: "South America" },
  { location: "Pernambuco", country: "Brazil", continent: "South America" },
  { location: "Rio de Janeiro", country: "Brazil", continent: "South America" },
  { location: "Nationwide", country: "Brazil", continent: "South America" },
  { location: "Buenos Aires", country: "Argentina", continent: "South America" },
  { location: "Nationwide", country: "Argentina", continent: "South America" },
  { location: "Bogotá", country: "Colombia", continent: "South America" },
  { location: "Medellin", country: "Colombia", continent: "South America" },
  { location: "Nationwide", country: "Chile", continent: "South America" },
  { location: "Antofagasta", country: "Chile", continent: "South America" },
  { location: "Santiago", country: "Chile", continent: "South America" },
  { location: "santiago", country: "Chile", continent: "South America" },
  { location: "Nationwide", country: "South Africa", continent: "Africa" },
  { location: "Gauteng", country: "South Africa", continent: "Africa" },
  { location: "Nationwide", country: "Nigeria", continent: "Africa" },
  { location: "Lagos", country: "Nigeria", continent: "Africa" },
  { location: "Imo", country: "Nigeria", continent: "Africa" },
  { location: "Cairo", country: "Egypt", continent: "Africa" },
  { location: "Nationwide", country: "Egypt", continent: "Africa" },
  { location: "Casablanca", country: "Morocco", continent: "Africa" },
  { location: "Nationwide", country: "Morocco", continent: "Africa" },
  { location: "Nationwide", country: "Kenya", continent: "Africa" },
  { location: "Nationwide", country: "Australia", continent: "Oceania" },
  { location: "NSW", country: "Australia", continent: "Oceania" },
  { location: "Victoria", country: "Australia", continent: "Oceania" },
  { location: "Auckland", country: "New Zealand", continent: "Oceania" },
  { location: "Nationwide", country: "New Zealand", continent: "Oceania" },
  { location: "Kanagawa", country: "Japan", continent: "Asia" },
  { location: "Tokyo", country: "Japan", continent: "Asia" },
  { location: "Taipei", country: "Taiwan", continent: "Asia" },
  { location: "Nationwide", country: "Taiwan", continent: "Asia" },
  { location: "Nationwide", country: "Hong Kong", continent: "Asia" },
  { location: "Macao", country: "Macau", continent: "Asia" },
  { location: "Nationwide", country: "Macau", continent: "Asia" },
  { location: "Macao, Sar Of China", country: "Macau", continent: "Asia" },
  { location: "Kwangsi", country: "China", continent: "Asia" },
  { location: "Shenzhen", country: "China", continent: "Asia" },
].freeze

RADIOS = [
  { name: "Cadena 100", website: "http://www.cadena100.es/", url: "http://cadena100-streamers-mp3.flumotion.com/cope/cadena100.mp3", gender: "Music", location_index: 0 },
  { name: "Ibiza Global Radio", website: "http://www.ibizaglobalradio.com/", url: "http://ibizaglobalradio.streaming-pro.com:8024/", gender: "Dance", location_index: 1 },
  { name: "LOS 40 Principales España", website: "https://los40.com/", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/Los40.mp3", gender: "Music", location_index: 0 },
  { name: "Chocolate FM", website: "https://www.chocolatefm.com/", url: "http://streaming5.elitecomunicacion.es:8082/live.mp3", gender: "Chr", location_index: 2 },
  { name: "Cadena SER España", website: "http://play.cadenaser.com/", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3", gender: "Cultural News", location_index: 0 },
  { name: "Rai Radio 1", website: "http://www.radio1.rai.it/", url: "http://icestreaming.rai.it/1.mp3", gender: "News", location_index: 3 },
  { name: "Virgin Radio Classic Rock", website: "http://www.virginradio.it/sezioni/1219/virgin-radio-rock-classic", url: "http://icy.unitedradio.it/VirginRockClassics.mp3", gender: "Classic Rock", location_index: 4 },
  { name: "Radio 24 il sole 24 ore", website: "https://www.radio24.ilsole24ore.com/", url: "http://shoutcast2.radio24.it:8000/;", gender: "News Talk", location_index: 5 },
  { name: "Radio 105 Network", website: "http://www.105.net/", url: "http://icecast.unitedradio.it/Radio105.mp3", gender: "Hits", location_index: 4 },
  { name: "Rai Radio 2", website: "http://www.radio2.rai.it/", url: "http://icestreaming.rai.it/2.mp3", gender: "Public Radio", location_index: 3 },
  { name: "France Info", website: "https://www.francetvinfo.fr/", url: "http://direct.franceinfo.fr/live/franceinfo-midfi.mp3", gender: nil, location_index: 6 },
  { name: "RFI Afrique", website: "http://www.rfi.fr/", url: "http://live02.rfi.fr/rfiafrique-64.mp3", gender: "Africa", location_index: 6 },
  { name: "RMC FR", website: "https://rmc.bfmtv.com/", url: "https://audio.bfmtv.com/rmcradio_128.mp3", gender: "France", location_index: 6 },
  { name: "Jazz Radio Blues", website: "http://www.jazzradio.fr/radio/webradio/3/blues", url: "http://jazzblues.ice.infomaniak.ch/jazzblues-high.mp3", gender: "Blues", location_index: 6 },
  { name: "France Inter", website: "https://www.franceinter.fr/", url: "http://direct.franceinter.fr/live/franceinter-hifi.aac", gender: nil, location_index: 6 },
  { name: "MANGORADIO", website: "https://mangoradio.de/", url: "https://mangoradio.stream.laut.fm/mangoradio", gender: "Music", location_index: 7 },
  { name: "Rock Antenne - Heavy Metal", website: "http://www.rockantenne.de/", url: "http://mp3channels.webradio.rockantenne.de/heavy-metal", gender: "Heavy Metal", location_index: 8 },
  { name: "1LIVE", website: "https://einslive.de/", url: "http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3", gender: "Ard", location_index: 9 },
  { name: "80s80s", website: "http://80s80s.de/", url: "http://streams.80s80s.de/web/mp3-192/streams.80s80s.de/", gender: "80s", location_index: 10 },
  { name: "90s90s Hits", website: "http://www.90s90s.de/", url: "http://streams.90s90s.de/pop/mp3-192/streams.90s90s.de/", gender: "90s", location_index: 10 },
  { name: "BBC World Service", website: "https://www.bbc.co.uk/programmes/w172xzjgf6lxp7y", url: "http://stream.live.vc.bbcmedia.co.uk/bbc_world_service", gender: "News", location_index: 11 },
  { name: "Classic FM UK", website: "http://www.classicfm.com/", url: "http://ice-the.musicradio.com/ClassicFMMP3", gender: "Classical", location_index: 12 },
  { name: "LBC Radio", website: "http://www.lbc.co.uk/", url: "http://media-sov.musicradio.com/LBC973MP3Low", gender: "Political Talk", location_index: 11 },
  { name: "Radio Caroline", website: "http://www.radiocaroline.co.uk/", url: "http://78.129.202.200:8040/;", gender: "Country", location_index: 11 },
  { name: "Capital FM London", website: "http://www.capitalfm.com/london/", url: "http://media-ice.musicradio.com/CapitalMP3", gender: "Pop", location_index: 12 },
  { name: "ORBITAL", website: "http://www.orbital.pt/", url: "http://centova.radios.pt:8401/;listen.pls", gender: "Dance", location_index: 13 },
  { name: "Antena 1 (Portugal)", website: "https://www.rtp.pt/play/direto/antena1", url: "http://streaming-live-app.rtp.pt/liveradio/antena180a/playlist.m3u8", gender: "Portugal", location_index: 14 },
  { name: "RFM", website: "https://rfm.sapo.pt/", url: "https://23603.live.streamtheworld.com/RFMAAC.aac", gender: "64kbps", location_index: 14 },
  { name: "Rádio Observador", website: "https://observador.pt/", url: "http://195.23.85.126:8455/stream", gender: nil, location_index: 13 },
  { name: "Rádio Renascença", website: "http://rr.sapo.pt/", url: "http://27783.live.streamtheworld.com:3690/RADIO_RENASCENCA_SC", gender: "National News", location_index: 13 },
  { name: "Intense Radio - We love Dance 256K", website: "https://www.intenseradio.net/", url: "https://secure.live-streams.nl/main", gender: "Clubhouse", location_index: 15 },
  { name: "NPO Radio 1", website: "http://www.radio1.nl/", url: "http://icecast.omroep.nl/radio1-bb-mp3", gender: "News", location_index: 16 },
  { name: "NPO Radio 2", website: "http://www.nporadio2.nl/", url: "http://icecast.omroep.nl/radio2-bb-mp3", gender: "Evergreens", location_index: 16 },
  { name: "Arrow Classic Rock", website: "https://www.arrow.nl/", url: "http://stream.gal.io/arrow", gender: "Classic Rock", location_index: 16 },
  { name: "Radio 10", website: "https://www.radio10.nl/", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/RADIO10.mp3", gender: "00's", location_index: 16 },
  { name: "Sveriges Radio - P1", website: "https://sverigesradio.se/", url: "https://live1.sr.se/p1-aac-320", gender: "News", location_index: 17 },
  { name: "Mix Megapol", website: "http://www.mixmegapol.se/", url: "http://tx-bauerse.sharp-stream.com/http_live.php?ua=WEB&i=mixmegapol_instream_se_mp3", gender: nil, location_index: 17 },
  { name: "NRJ Sweden", website: "http://www.nrj.se/", url: "http://tx-bauerse.sharp-stream.com/http_live.php?i=nrj_instreamtest_se_mp3", gender: "Top 40", location_index: 17 },
  { name: "Country Rocks Radio", website: "http://www.countryrocksradio.com/", url: "http://stream.dbmedia.se/crr96", gender: "Country", location_index: 18 },
  { name: "Pirate Rock  Västkustens bästa rock", website: "https://piraterock.se/", url: "http://stream.piraterock.se:8101/webradio", gender: "Classic Rock", location_index: 17 },
  { name: "RMF FM", website: "https://www.rmf.fm/", url: "http://195.150.20.242:8000/rmf_fm", gender: "Fm", location_index: 19 },
  { name: "Radio Zet", website: "https://www.radiozet.pl/", url: "http://zet-net-01.cdn.eurozet.pl:8400/", gender: nil, location_index: 19 },
  { name: "Antyradio", website: "http://www.antyradio.pl/", url: "https://n-4-2.dcs.redcdn.pl/sc/o2/Eurozet/live/antyradio.livx?audio=5", gender: "Metal", location_index: 19 },
  { name: "Polskie Radio Jedynka", website: "http://www.polskieradio.pl/jedynka/", url: "http://mp3.polskieradio.pl:8900/;.mp3", gender: "Polskieradio", location_index: 19 },
  { name: "Polskie Radio 24", website: "http://www.polskieradio.pl/130,PR24", url: "http://stream3.polskieradio.pl:8080/;.mp3", gender: "Information", location_index: 19 },
  { name: "Blues Radio", website: "http://bluesradio.gr/", url: "http://cast3.radiohost.ovh:8352/", gender: "Blues", location_index: 20 },
  { name: "KISS FM 100.6", website: "http://www.radiokiss.gr/", url: "http://live.radiokiss.gr/kissfm1006hq.mp3", gender: "00s", location_index: 21 },
  { name: "Real FM 97.8", website: "http://www.real.gr/", url: "http://netradio.live24.gr/realfm", gender: "Greek", location_index: 20 },
  { name: "Trance Athena", website: "https://www.tranceathena.com/", url: "http://cast.streams.ovh:8008/stream", gender: "Electronic", location_index: 22 },
  { name: "Kiss 92.9", website: "http://www.kiss929.gr/", url: "http://netradio.live24.gr/kissfmathens", gender: "Pop", location_index: 20 },
  { name: "Jazz Sakura (asia dream radio)", website: "https://asiadreamradio.torontocast.stream/stations/en/index.html", url: "http://kathy.torontocast.com:3330/stream/1/?esPlayer&cb=82181.mp3", gender: "Japanese", location_index: 23 },
  { name: "Anime Para Ti", website: "https://www.facebook.com/radioanimeparati", url: "https://stream.zeno.fm/qpn8mkt8c4duv", gender: "Anime", location_index: 23 },
  { name: "Listen.Moe JPop Vorbis", website: "https://listen.moe/", url: "https://listen.moe/stream", gender: "Jpop", location_index: 23 },
  { name: "Gensokyo Radio", website: "https://gensokyoradio.net/", url: "https://stream.gensokyoradio.net/3", gender: "Anime", location_index: 23 },
  { name: "Retro PC GAME MUSIC Streaming Radio", website: "http://gyusyabu.ddo.jp/MP3/MP3.html", url: "http://gyusyabu.ddo.jp:8000/", gender: "Chiptune", location_index: 23 },
  { name: "华语金曲500首", website: "https://m.qingting.fm/", url: "http://ls.qingting.fm/live/3412131.m3u8?bitrate=64", gender: "Golden Music", location_index: 24 },
  { name: "CCTV-13新闻伴音", website: "https://www.cctv.com/", url: "https://piccpndali.v.myalicdn.com/audio/cctv13_2.m3u8", gender: "Tv", location_index: 24 },
  { name: "凤凰卫视资讯台", website: "https://www.ifeng.com/", url: "http://playtv-live.ifeng.com/live/06OLEEWQKN4_audio.m3u8", gender: "News", location_index: 24 },
  { name: "怀集音乐之声", website: "http://www.hj0758.cn/", url: "https://lhttp.qingting.fm/live/4804/64k.mp3", gender: "Music", location_index: 25 },
  { name: "CNR-1 中国之声", website: "http://www.cnr.cn/", url: "https://lhttp.qtfm.cn/live/15318317/64k.mp3", gender: "News", location_index: 24 },
  { name: "Bollywood Gaane Purane", website: "https://gaanepurane.my-free.website/", url: "https://stream.zeno.fm/6n6ewddtad0uv", gender: nil, location_index: 26 },
  { name: "Fnf.Fm Hindi", website: "http://hi.fnf.fm/?m=1", url: "http://192.99.8.192:5032/;stream", gender: "Bollywood", location_index: 26 },
  { name: "MY RADIO DJ", website: "http://zeno.fm/myradiodj", url: "http://stream.zeno.fm/84h97t3ewg0uv", gender: nil, location_index: 27 },
  { name: "Radio BollyFm", website: "http://www.radiobollyfm.in/", url: "http://stream.radiobollyfm.in:8201/hd?t=1526570335", gender: nil, location_index: 28 },
  { name: "Goldy Evergreen", website: "https://zeno.fm/goldy-fm/", url: "https://stream.zeno.fm/n2fd0edh9k8uv", gender: nil, location_index: 26 },
  { name: "Listen.moe Kpop", website: "https://listen.moe/kpop", url: "https://listen.moe/kpop/stream", gender: "Kpop", location_index: 29 },
  { name: "Big B Radio - Kpop", website: "https://bigbradio.net/kpop", url: "https://antares.dribbcast.com/proxy/kpop?mp=/s", gender: "Music", location_index: 29 },
  { name: "KBS Classic FM", website: "http://www.kbs.co.kr/", url: "https://1fm.gscdn.kbs.co.kr/1fm_192_2.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly8xZm0uZ3NjZG4ua2JzLmNvLmtyLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3ODkyNTAzNTh9fX1dfQ__&Key-Pair-Id=APKAICDSGT3Y7IXGJ3TA&Signature=QythqpFEAmrrVpalN2lR0nkAq6yWNPTVcv1iw42dRJzkMfzzGrplbcydx~b7tmvKbzm42ygls3UNoCKrB2j01dB8SU0HXUeStFASZsWv8HoHTSAreQn5wU5TynLCYl-rAhpF3UiqyI4-rfB-3vMIwiugn1pIGkHW4VoajzjJsKC0f3Ii5kH8rr4ql1-H4PCFIq4utU5DqnMWDAxC4ik1nbQY2jHrcpXdwMnGCd5YM5QVS6W3rwOTNAOZazHHj7Tj~qcngmcp3~OCg3Xauxs9FIs07QEBdtoPibNSG4iFzB-5IfSZfFniVT-oZlXixTbHKQVEQOD75ONev9W6XGAhSA__", gender: nil, location_index: 30 },
  { name: "Oldpop Cafe", website: "https://oldpopcafe.net/", url: "http://cast.oldpopcafe.net:7080/", gender: "Oldies", location_index: 30 },
  { name: "MBC FM4U", website: "http://www.imbc.com/", url: "https://minimw.imbc.com/dmfm/_definst_/mfm.stream/playlist.m3u8?_lsu_sa_=6621BF12B3513564B543352E31414B40B5B639A5CE0092123FC0D9a896883A66E7a4736F33F2B542F03E34F115b9E15FABE43F73BE158DD2AA46AAA05E74D159710608A4DA660CB753387D8E67062A9C457A9127747D9B0D500F3B8B4D33C19C653133E1A666FE055D3CA14475C1E8B1", gender: nil, location_index: 30 },
  { name: "90 rakthai", website: "http://radio11.plathong.net:8896/;stream.mp3", url: "http://radio11.plathong.net:8896/;stream.mp3", gender: nil, location_index: 31 },
  { name: "มิติข่าว 90.5", website: "http://www.smartbomb.co.th/", url: "http://live3.smartbomb.co.th:8624/;stream.mp3", gender: "News", location_index: 32 },
  { name: "Cool fahrenheit", website: "http://www.coolism.net/index.php", url: "https://coolism-web.cdn.byteark.com/;stream/1", gender: nil, location_index: 31 },
  { name: "ไทยลานนาเรดิโอ FM 106.5 จังหวัดตาก", website: "https://www.lannaradio.com/", url: "https://inter.lannaradio.com/radio/8000/radio.mp3", gender: "Country", location_index: 33 },
  { name: "Thai PBS TV", website: "http://www.thaipbs.or.th/", url: "http://thaipbs-live.cdn.byteark.com/live-en/playlist_720p/index.m3u8", gender: nil, location_index: 32 },
  { name: "I-Radio Jakarta", website: "http://iradiofm.com/", url: "http://stream.radiojar.com/4ywdgup3bnzuv", gender: "Indonesia", location_index: 34 },
  { name: "RDI 97.1 FM", website: "http://www.rdifm.co.id/", url: "http://202.147.199.99:8000/;stream/1", gender: "Dangdut", location_index: 34 },
  { name: "Suara Giri 98.4 FM", website: "http://www.girifm.com/", url: "http://streaming.girifm.com:8010/", gender: "Pop", location_index: 35 },
  { name: "elshinta  jakarta", website: "https://elshinta.com/radio", url: "https://stream-ssl.arenastreaming.com:8000/jakarta", gender: "News", location_index: 35 },
  { name: "Wijaya FM 103.5 FM Surabaya", website: "https://radiowijayafm.com/", url: "http://wijayafm.onlivestreaming.net:9880/stream?", gender: "Undefined", location_index: 36 },
  { name: "Star FM Manila", website: "http://www.bomboradyo.com/starfmmanila/", url: "https://stream-13.zeno.fm/g1pmt17nz9duv", gender: nil, location_index: 37 },
  { name: "Barangay LS 97.1 Manila", website: "https://www.gmanetwork.com/radio/streaming/dwls", url: "http://28093.live.streamtheworld.com:3690/MORFM_S01AAC_SC", gender: "Opm", location_index: 38 },
  { name: "Christmas Radio Philippines - Powered By www.amfmph.net", website: "https://www.amfmph.com/", url: "https://us1.amfmph.com/ssl/christmasradio?mp=/stream&1641738050672", gender: "Christmas Music", location_index: 37 },
  { name: "MOR Entertainment", website: "https://www.onemusic.ph/listen-now/radio", url: "https://stream-37.zeno.fm/26ea0anpms8uv", gender: "Internet Radio", location_index: 37 },
  { name: "Bombo Radyo Iloilo", website: "https://www.bomboradyo.com/", url: "https://stream.zenolive.com/gzudz59nz9duv", gender: "News", location_index: 37 },
  { name: "Radio 103FM", website: "https://103fm.maariv.co.il/", url: "https://cdn.cybercdn.live/103FM/Live/icecast.audio", gender: nil, location_index: 39 },
  { name: "Galei Zahal", website: "http://glzwizzlv.bynetcdn.com/", url: "http://glzwizzlv.bynetcdn.com/glz_mp3", gender: nil, location_index: 39 },
  { name: "Glglz", website: "https://glz.co.il/%D7%92%D7%9C%D7%92%D7%9C%D7%A6", url: "https://api.bynetcdn.com/Redirector/glz/glglz/ICE-LIVE", gender: nil, location_index: 39 },
  { name: "اذاعة الشمس - A-Shams", website: "https://www.ashams.com/", url: "https://cdna.streamgates.net/Ashams/Live/icecast.audio", gender: "Ilstations", location_index: 39 },
  { name: "Первое радио 89.1FM", website: "https://www.891fm.co.il/", url: "https://cdn.cybercdn.live/Pervoia/Audio/icecast.audio", gender: "Pop", location_index: 39 },
  { name: "ChroniX Radio Metalcore", website: "http://chronixradio.net/", url: "http://usa17.fastcast4u.com:5508/stream", gender: "Death Metal", location_index: 40 },
  { name: "REGGAE CHILL CAFE", website: "https://radiosuitenetwork.torontocast.stream/", url: "https://maggie.torontocast.com:2020/stream/reggaechillcafe", gender: "Chill", location_index: 41 },
  { name: "Calm Radio - Solo Piano", website: "https://www.calmradio.com/", url: "http://streams.calmradio.com:1228/", gender: "Easy Listening", location_index: 41 },
  { name: "680 News Toronto", website: "https://www.680news.com/", url: "https://rogers-hls.leanstream.co/rogers/tor680.stream/playlist.m3u8", gender: nil, location_index: 41 },
  { name: "CFRB News/Talk 1010 (Toronto, ON)", website: "https://www.iheartradio.ca/newstalk-1010", url: "http://18233.live.streamtheworld.com:3690/CFRBAMAAC_SC", gender: "Commercial", location_index: 41 },
  { name: "Radio Paradise Main Mix (EU) 320k AAC", website: "https://radioparadise.com/", url: "http://stream-uk1.radioparadise.com/aac-320", gender: "California", location_index: 42 },
  { name: "Classic Vinyl HD", website: "https://walmradio.com/classic", url: "https://icecast.walmradio.com:8443/classic", gender: "1930", location_index: 43 },
  { name: "Adroit Jazz Underground", website: "https://walmradio.com/jazz", url: "https://icecast.walmradio.com:8443/jazz", gender: "Avant-garde", location_index: 44 },
  { name: "Christmas Vinyl HD", website: "https://walmradio.com/christmas", url: "https://icecast.walmradio.com:8443/christmas", gender: "Christian", location_index: 43 },
  { name: "WALM HD", website: "https://walmradio.com/walm", url: "https://icecast.walmradio.com:8443/walm", gender: "Christian", location_index: 43 },
  { name: "Los 40 Principales México", website: "http://los40.com.mx/", url: "http://15723.live.streamtheworld.com/LOS40_MEXICO_SC", gender: "Hits", location_index: 45 },
  { name: "BEAUTIFUL Instrumentals", website: "https://beautifulmusicstation.blogspot.com/", url: "http://s3.voscast.com:10038/", gender: "Classical", location_index: 46 },
  { name: "Oldies Internet Radio", website: "https://oldiesinternetradio.com/", url: "http://162.244.81.98:8140/listen", gender: "1970s", location_index: 46 },
  { name: "XHEXA \"Exa FM\" 104.9 FM Mexico City, DF", website: "http://www.exafm.com/#!/mexico/home", url: "http://18303.live.streamtheworld.com/XHEXA_SC", gender: "Electronica", location_index: 47 },
  { name: "Antena 1 São Paulo, SP (ZYD823 94,7 MHz FM) [aac]", website: "http://antena1.com.br/", url: "http://antena1.newradio.it/stream?ext=.mp3", gender: "Adult Contemporary", location_index: 48 },
  { name: "Rádio Flashback Fm", website: "http://flashbackfmst.com.br/", url: "http://hd.matutos.com.br:8008/;stream.mp3", gender: "Brasil", location_index: 49 },
  { name: "Antena 1 FM 94.7 São Paulo", website: "https://www.antena1.com.br/", url: "http://antena1.newradio.it/stream", gender: "Adult Contemporary", location_index: 48 },
  { name: "Antena 1 FM 103.7 Rio de Janeiro", website: "https://www.antena1rio.com.br/", url: "http://a1rj.streams.com.br:7801/stream", gender: "Adult Contemporary", location_index: 50 },
  { name: "Rádio Bossa Nova Brazil", website: "http://www.vip-radios.fm/station/bossa-nova-brazil/", url: "http://54.38.43.201:8009/stream-128kmp3-BossaNovaBrazil", gender: "Bossa Nova", location_index: 51 },
  { name: "Radio Rivadavia", website: nil, url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIA.mp3", gender: nil, location_index: 52 },
  { name: "Rock And Pop FM 95.9 (Rock & Pop) Ciudad de Buenos Aires", website: "https://fmrockandpop.com/", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/ROCKANDPOPAAC.aac", gender: nil, location_index: 53 },
  { name: "Mitre AM 790. AAC Alta. Ciudad de Buenos Aires", website: "https://radiomitre.cienradios.com/", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/AM790_56AAC.aac", gender: nil, location_index: 53 },
  { name: "Radio Rivadavia AM 630. Ciudad de Buenos Aires", website: "https://rivadavia.com.ar/", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac", gender: nil, location_index: 53 },
  { name: "La 100 - 99.9 FM - Grupo Clarín - Buenos Aires, Argentina", website: "https://la100.cienradios.com/", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/FM999_56.mp3", gender: "99.9 Fm", location_index: 52 },
  { name: "La Kalle", website: "http://lakalle.bluradio.com/", url: "http://24503.live.streamtheworld.com:3690/LA_KALLE_SC", gender: "Folk Music", location_index: 54 },
  { name: "123 Vallenato", website: "http://www.radios.com.co/vallenato/", url: "http://radiolatina.info:7087/;", gender: nil, location_index: 55 },
  { name: "Radiónica (HJYM 99.1 Bogotá) RTVC", website: "http://www.radionica.rocks/", url: "http://shoutcast.rtvc.gov.co:8010/;", gender: "Electronic", location_index: 54 },
  { name: "Tropicana Bogotá (HJRX 102.9) Caracol Radio", website: "http://www.tropicanafm.com/", url: "http://27393.live.streamtheworld.com/TROPICANA_SC", gender: "Salsa", location_index: 54 },
  { name: "Candela Estéreo Bogotá (HJPU 101.9)", website: "http://www.candelaestereo.com/", url: "http://27373.live.streamtheworld.com/CANDELAESTEREO_SC", gender: "Bogota", location_index: 54 },
  { name: "La Retro 80s Chile", website: "https://www.laretro.cl/", url: "https://s2.radio.co:80/s9ecef4f68/listen", gender: "1980s", location_index: 56 },
  { name: "BioBio Chile", website: "https://www.biobiochile.cl/", url: "https://unlimited3-cl.dps.live/biobiosantiago/aac/icecast.audio", gender: "News", location_index: 56 },
  { name: "Radio Sol Classic", website: "https://radiosol.cl/", url: "https://us9.maindigitalstream.com/ssl/radiosol", gender: nil, location_index: 57 },
  { name: "Imagina", website: "http://www.radioimagina.cl/", url: "http://27433.live.streamtheworld.com:3690/IMAGINA_SC", gender: "Hits", location_index: 58 },
  { name: "Corazon", website: nil, url: "http://27693.live.streamtheworld.com:3690/CORAZON_SC", gender: nil, location_index: 59 },
  { name: "Jacaranda FM", website: "https://www.jacarandafm.com/", url: "https://edge.iono.fm/xice/jacarandafm_live_medium.aac", gender: "Adult Contemporary", location_index: 60 },
  { name: "Bosveld Stereo", website: "http://www.bosveldstereo.co.za/", url: "http://capeant.antfarm.co.za:8000/Bosveld", gender: "Pop", location_index: 60 },
  { name: "94.7", website: "http://www.947.co.za/", url: "http://25503.live.streamtheworld.com:3690/FM947AAC_SC", gender: "Classic Hits", location_index: 61 },
  { name: "702 Johannesburg", website: "http://www.702.co.za/", url: "http://28033.live.streamtheworld.com:3690/FM702_SC", gender: "Johannesburg", location_index: 61 },
  { name: "Amapiano FM", website: "https://radiosa.org/amapiano/", url: "https://stream.zeno.fm/xs6zeac1ts8uv", gender: nil, location_index: 60 },
  { name: "RFI Haoussa", website: "http://www.rfi.fr/", url: "http://live02.rfi.fr/rfihaoussa-96k.mp3", gender: nil, location_index: 62 },
  { name: "Nigerian Gospel Music Radio (MP3)", website: "https://nigeriangospelmusic.com.ng/", url: "http://stream.zeno.fm/3fmqr74a7f8uv", gender: "Christian", location_index: 63 },
  { name: "Radio East", website: "https://www.radioeast.com.ng/", url: "http://stream.zeno.fm/7f4w4us5wp8uv", gender: "Music", location_index: 64 },
  { name: "METRO FM LAGOS", website: "https://go.webgateready.com/metrofm/radio.mp3", url: "https://go.webgateready.com/metrofm/radio.mp3", gender: nil, location_index: 62 },
  { name: "MajorFM", website: "https://zeno.fm/radio/major-fm/", url: "http://stream.zeno.fm/pkza99xshkhvv", gender: "80s", location_index: 63 },
  { name: "إذاعة القرآن الكريم من القاهرة", website: "http://n12.radiojar.com/8s5u5tpdtwzuv?listening-from-radio-garden=1620219571863&rj-tok=AAABeTyl2zYARSWbLVnrEOlqGw&rj-ttl=5", url: "http://n12.radiojar.com/8s5u5tpdtwzuv?listening-from-radio-garden=1620219571863&rj-tok=AAABeTyl2zYARSWbLVnrEOlqGw&rj-ttl=5", gender: "اسلامي", location_index: 65 },
  { name: "Radio 9090 90.9", website: "http://www.9090.fm/", url: "http://9090streaming.mobtada.com/9090FMEGYPT", gender: nil, location_index: 65 },
  { name: "إذاعة محمود خليل الحصري", website: "http://www.phantomsw.com/", url: "https://qurango.net/radio/mahmoud_khalil_alhussary_warsh", gender: nil, location_index: 66 },
  { name: "On sports FM", website: "http://www.onsportfm.com/", url: "https://carina.streamerr.co:2020/stream/OnSportFM", gender: nil, location_index: 66 },
  { name: "إذاعة مشاري العفاسي", website: "http://www.phantomsw.com/", url: "https://qurango.net/radio/mishary_alafasi", gender: nil, location_index: 66 },
  { name: "Radio Aswat", website: "http://www.radioaswat.ma/", url: "http://broadcast.ice.infomaniak.ch/aswat-high.mp3?.mp3", gender: nil, location_index: 67 },
  { name: "bldi", website: nil, url: "http://beldifm.hf.ma/radio/8000/radio.mp3", gender: "Classical", location_index: 68 },
  { name: "Only rai", website: "http://www.urbanhit.fr/#", url: "http://onlyrai.ice.infomaniak.ch/onlyrai-high.mp3", gender: nil, location_index: 68 },
  { name: "MA:-Hit Radio Maroc", website: "https://stream.zeno.fm/une3a02mb", url: "https://stream.zeno.fm/une3a02mb", gender: "Classical", location_index: 68 },
  { name: "Fayroz", website: "https://radio.ma.co/", url: "https://stream.zeno.fm/zv3e5wykprhvv.mp3", gender: "Classical", location_index: 68 },
  { name: "NRG Radio", website: "https://nrg.radio/", url: "https://streamingv2.shoutcast.com/nrg-radio-ke", gender: "Pop", location_index: 69 },
  { name: "Kameme FM", website: "https://www.mediamax.app/kameme-fm", url: "https://kamemefm-atunwadigital.streamguys1.com/kamemefm", gender: nil, location_index: 69 },
  { name: "REGGAE ROOTS", website: "http://relay5.181.fm:8096/", url: "http://relay5.181.fm:8096/", gender: "Classical", location_index: 69 },
  { name: "KBC", website: nil, url: "http://stream.zeno.fm/ud2u96xst5quv", gender: "Classical", location_index: 69 },
  { name: "ghetto kenya", website: "https://stream.zeno.fm/kvudezx1h2zuv", url: "https://stream.zeno.fm/kvudezx1h2zuv", gender: "Classical", location_index: 69 },
  { name: "ABC NewsRadio MP3", website: "http://www.abc.net.au/newsradio/", url: "http://abc.streamguys1.com/live/newsradio/icecast.audio", gender: "Abc", location_index: 70 },
  { name: "ABC News Radio", website: "http://www.abc.net.au/newsradio/", url: "http://abc.streamguys1.com/live/newsradio/icecast.audio", gender: nil, location_index: 71 },
  { name: "Kiss FM 87.6, 87.8 & 88.0 Melbourne, VIC", website: "https://kissfm.com.au/", url: "http://cc.net2streams.com:8565/kissfm.mp3", gender: "Dance", location_index: 72 },
  { name: "ABC Radio National AAC+", website: "http://www.abc.net.au/radionational/", url: "http://abc.streamguys1.com/live/rnnsw/icecast.audio", gender: "Abc", location_index: 70 },
  { name: "The Prog Rock Machine", website: "https://progrockmachine.com/", url: "https://theproganrockmachine.out.airtime.pro/theproganrockmachine_b", gender: "Progressive Rock", location_index: 70 },
  { name: "RNZ National MP3", website: "https://www.rnz.co.nz/national", url: "http://radionz-ice.streamguys.com/national.mp3", gender: "Features", location_index: 73 },
  { name: "Easy 80s", website: "https://www.auckland80s.com/easy-80s.html", url: "http://procyon.shoutca.st:8032/;", gender: "80s", location_index: 74 },
  { name: "Wandering Sheep Radio - Christian Smooth Jazz", website: "https://wsradio.net/", url: "http://radio.wanderingsheep.tv:8021/christianjazz", gender: "Christian", location_index: 73 },
  { name: "Newstalk ZB Wellington", website: "https://www.newstalkzb.co.nz/", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/NZME_31AAC.m3u8", gender: "Local News", location_index: 74 },
  { name: "RNZ Pacific MP3", website: "https://www.rnz.co.nz/international", url: "http://radionz-ice.streamguys.com/international.mp3", gender: "Features", location_index: 73 },
  { name: "R/a/dio", website: "http://r-a-d.io/", url: "https://relay0.r-a-d.io/main.mp3", gender: "Anime", location_index: 23 },
  { name: "J1 Gold (HTTP)", website: "https://en.j1fm.tokyo/", url: "http://jenny.torontocast.com:8062/", gender: "Jpop", location_index: 23 },
  { name: "Shonan Beach FM 78.9", website: "https://www.beachfm.co.jp/", url: "http://shonanbeachfm.out.airtime.pro:8000/shonanbeachfm_a", gender: "Classic Jazz", location_index: 75 },
  { name: "Free FM Tokyo", website: "http://freefmradio.net/", url: "https://rocafmadrid.radioca.st/", gender: "Free Fm", location_index: 76 },
  { name: "Free FM 80 Tokyo", website: "http://www.freefmworld.com/", url: "https://freefm80.radioca.st/", gender: "#80s", location_index: 76 },
  { name: "J1 Hits (HTTP)", website: "https://en.j1fm.tokyo/", url: "http://jenny.torontocast.com:8056/", gender: nil, location_index: 23 },
  { name: "BOX : Japan City Pop - 日本のシティポップ", website: "https://boxradio.net/", url: "https://play.streamafrica.net/japancitypop", gender: "City Pop", location_index: 23 },
  { name: "Nightwave Plaza OPUS 96", website: "http://radio.plaza.one/", url: "http://radio.plaza.one/opus", gender: "Aesthetic", location_index: 23 },
  { name: "Ottava", website: "https://ottava.jp/", url: "http://ottava2.out.airtime.pro:8000/ottava2_a", gender: "Classical", location_index: 76 },
  { name: "Big B Radio - Jpop", website: "https://bigbradio.net/jpop", url: "https://antares.dribbcast.com/proxy/jpop?mp=/s", gender: "Music", location_index: 23 },
  { name: "Súper Tokio Radio", website: "https://supertokio.com/", url: "https://streamer.radio.co/s83eb8ff39/listen", gender: "International", location_index: 23 },
  { name: "Fred Film Radio(日本語)", website: "http://www.fred.fm/", url: "https://s10.webradio-hosting.com/proxy/fredradiojp/stream", gender: "Culture", location_index: 76 },
  { name: "Moon Mission Recordings", website: "https://www.moonmission.jp/", url: "http://uk5.internet-radio.com:8306/", gender: "Deep House", location_index: 23 },
  { name: "NHK-FM", website: "https://www.nhk.or.jp/radio/", url: "http://mnet.x10.mx/nhkfm.m3u8", gender: "Classical", location_index: 23 },
  { name: "Nightwave Plaza MP3 182", website: "https://plaza.one/", url: "http://radio.plaza.one/mp3", gender: nil, location_index: 23 },
  { name: "J-POP Powerplay", website: "http://www.asiadreamradio.com/stations/en/", url: "https://kathy.torontocast.com:3560/", gender: "Pop", location_index: 23 },
  { name: "Listen.moe J-Pop (MP3)", website: "https://listen.moe/", url: "https://listen.moe/fallback", gender: nil, location_index: 23 },
  { name: "OnlyHits Japan", website: "https://j.onlyhit.us/", url: "https://j.onlyhit.us/play", gender: nil, location_index: 23 },
  { name: "J-Rock Powerplay(Asia DREAM Radio)", website: "http://asiadreamradio.torontocast.stream/stations/en/index.html", url: "https://kathy.torontocast.com:3340/;?shoutcast", gender: "Music", location_index: 23 },
  { name: "J1 HITS", website: "https://www.j1fm.tokyo/", url: "https://jenny.torontocast.com:2000/stream/J1HITS?_=184325", gender: nil, location_index: 76 },
  { name: "臺北電台", website: "http://www.radio.gov.taipei/", url: "https://stream.ginnet.cloud/live0130lo-yfyo/_definst_/fm/playlist.m3u8", gender: "News", location_index: 77 },
  { name: "Classical 古典音樂台 FM 97.7", website: "http://www.family977.com.tw/index.php", url: "http://59.120.88.155:8000/live.mp3", gender: "Classical Music", location_index: 78 },
  { name: "中央廣播電台", website: "https://www.rti.org.tw/", url: "https://streamak0138.akamaized.net/live0138lh-mbm9/_definst_/rti3/chunklist.m3u8", gender: nil, location_index: 78 },
  { name: "Hit FM台北之音廣播", website: "https://www.hitoradio.com/newweb/onair.php", url: "http://202.39.43.67:1935/live/RA000036/chunklist.m3u8", gender: "Music", location_index: 78 },
  { name: "臺北電台AM", website: "http://www.radio.gov.taipei/", url: "https://stream.ginnet.cloud/live0130lo-yfyo/_definst_/am/playlist.m3u8", gender: "Public Radio", location_index: 78 },
  { name: "正聲廣播電台FM104", website: "https://www.csbc.com.tw/", url: "https://flv.ccdntech.com/live/_definst_/mp4:vod117_Live/live1/chunklist_w872521607.m3u8", gender: "Music", location_index: 77 },
  { name: "RTHK Radio 1", website: "https://www.rthk.hk/", url: "http://stm1.rthk.hk/radio1", gender: "Educational", location_index: 79 },
  { name: "RTHK Radio 2", website: "https://www.rthk.hk/", url: "http://stm2.rthk.hk/radio2", gender: "Entertainment", location_index: 79 },
  { name: "凤凰卫视中文台", website: "https://www.ifeng.com/", url: "http://playtv-live.ifeng.com/live/06OLEGEGM4G_audio.m3u8", gender: "News", location_index: 79 },
  { name: "RTHK Radio 5", website: "https://news.rthk.hk/rthk/en/", url: "https://rthkaudio5-lh.akamaihd.net/i/radio5_1@355868/index_56_a-p.m3u8", gender: "Education", location_index: 79 },
  { name: "Digital Radio Hong Kong", website: "http://digitalradiohk.net/", url: "http://ice.digitalradiohk.net:8000/drhk", gender: "Cantonese", location_index: 79 },
  { name: "夜空傳情", website: "https://open.spotify.com/show/08hLUNwvOdIXJjlXHiWm1r", url: "http://procyon.shoutca.st:8492/listen.mp3", gender: "Music", location_index: 79 },
  { name: "VOA Macau", website: "https://www.voachinese.com/", url: "https://voa-ingest.akamaized.net/hls/live/2035206/151_124L/playlist.m3u8", gender: "News", location_index: 80 },
  { name: "RADIO MARIA MACAU", website: "http://www.voiceofmary.org.mo/VoiceOfMary/jsp/index.jsp", url: "http://dreamsiteradiocp2.com:8038/stream", gender: "Catholic", location_index: 81 },
  { name: "Romance Radio 95.5 FM", website: "https://norilynonecoin.wixsite.com/criradioplayers-push", url: "http://162.220.162.10:8011/stream", gender: "Love Songs", location_index: 82 },
  { name: "Radio Top 80 Macau 強電台 - 89.9 FM", website: "https://www.top80.fm/", url: "http://live.top80.fm:8086/;", gender: "2000s", location_index: 82 },
  { name: "CityFM Macau - 90.5 FM", website: "https://m.qtfm.cn/", url: "https://lhttp.qtfm.cn/live/20500153/64k.mp3", gender: "Internet Radio", location_index: 82 },
  { name: "CGTN Radio - Macau 1341 AM", website: "https://radio.cgtn.com/", url: "https://sk.cri.cn/am846.m3u8", gender: "World News", location_index: 82 },
  { name: "CNR-2 经济之声", website: "http://www.cnr.cn/", url: "http://ngcdn002.cnr.cn/live/jjzs/index.m3u8", gender: "Economic", location_index: 24 },
  { name: "国际新闻", website: "http://www.ajmide.com/", url: "https://lhttp.qtfm.cn/live/20500172/64k.mp3", gender: "Information", location_index: 24 },
  { name: "清晨音乐台", website: "https://m.weibo.cn/u/2022851417", url: "http://lhttp.qingting.fm/live/4915/64k.mp3", gender: "Music", location_index: 83 },
  { name: "500首华语经典", website: "https://www.qingting.fm/radios/5022308", url: "https://lhttp.qtfm.cn/live/5022308/64k.mp3", gender: "Music", location_index: 24 },
  { name: "CRI中文环球广播·CRI chinese service", website: "http://chinese.cri.cn/radio/hyhq/index.html", url: "http://sk.cri.cn/hyhq.m3u8", gender: "International", location_index: 24 },
  { name: "深圳新闻广播", website: "http://www.szmg.com.cn/", url: "http://lhttp.qingting.fm/live/1270/64k.mp3", gender: "News", location_index: 84 },
  { name: "深圳音乐广播", website: "https://www.feiyang971.com/", url: "https://lhttp.qtfm.cn/live/1271/64k.mp3", gender: "Music", location_index: 84 },
  { name: "深圳交通广播", website: "http://www.szmg.com.cn/", url: "http://lhttp.qingting.fm/live/1272/64k.mp3", gender: "Traffic", location_index: 84 },
  { name: "深圳生活广播", website: "http://www.szmg.com.cn/", url: "http://lhttp.qingting.fm/live/1273/64k.mp3", gender: "News", location_index: 84 },
  { name: "深圳综艺广播", website: "http://www.szmg.com.cn/", url: "http://lhttp.qingting.fm/live/1271/64k.mp3", gender: "Music", location_index: 84 },
  { name: "深圳龙岗频道", website: "http://www.szmg.com.cn/", url: "http://lhttp.qingting.fm/live/20160/64k.mp3", gender: "Music", location_index: 84 },
].freeze

created_locations = LOCATIONS.map do |attrs|
  Location.find_or_create_by!(location: attrs[:location], country: attrs[:country]) do |loc|
    loc.continent = attrs[:continent]
  end
end

RADIOS.each do |attrs|
  location = created_locations[attrs[:location_index]]

  radio = Radio.find_or_create_by!(name: attrs[:name], location: location) do |r|
    r.website = attrs[:website]
    r.url = attrs[:url]
    r.gender = attrs[:gender]
  end

  next if attrs[:gender].blank?

  gender = Gender.find_or_create_by!(name: attrs[:gender])
  GendersRadio.find_or_create_by!(radio: radio, gender: gender)
end

puts "Seeded #{Location.count} locations, #{Radio.count} radios, #{Gender.count} genders."
